name: First CICD pipeline
on:
  push:
    branches: [main]   
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@3
     - name: Run a simple script
       run: echo "Hello Bindu, Fisrt CICD ran on Github actions"
